version: '2'
services:
  swarm-manager-1:
    container_name: swarm-manager-1
    hostname: swarm-manager-1
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  swarm-manager-2:
    container_name: swarm-manager-2
    hostname: swarm-manager-2
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  swarm-manager-3:
    container_name: swarm-manager-3
    hostname: swarm-manager-3
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  swarm-worker-1:
    container_name: swarm-worker-1
    hostname: swarm-worker-1
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  swarm-worker-2:
    container_name: swarm-worker-2
    hostname: swarm-worker-2
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  swarm-worker-3:
    container_name: swarm-worker-3
    hostname: swarm-worker-3
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  swarm-worker-4:
    container_name: swarm-worker-4
    hostname: swarm-worker-4
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  swarm-worker-5:
    container_name: swarm-worker-5
    hostname: swarm-worker-5
    image: docker:rc-dind
    mem_limit: 1G
    networks:
      - swarm-net
    privileged: true
  visualiser:
    container_name: visualiser
    image: manomarks/swarmvis:latest
    networks:
      - swarm-net
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=swarm-manager-1:2375
      - HOST=localhost 
networks:
  swarm-net:
